
#The message to be displayed during load. You can use multiple lines creating line breaks with \n. You can use colors using &
# %motd% gets replaced with whatever is in motd in server.properties
loading: The server is starting up. Please wait

#The messages to be displayed during runtime. You can use multiple lines creating line breaks with \n. You can use colors using &
# %motd% gets replaced with whatever is in motd in server.properties
# Each entry will be randomly chosen to display to a client upon pinging the server
messages:
 - "%motd%"
 
# The message displayed to users that attempt to join before
kickMessage: The server is starting up. Please try again soon.

# The number of ticks to wait after the first tick before the startup phase is considered to be over.
startupDelay: 300

# The maximum player value to report to a client upon pinging the server
maxplayers: 100
