name: ALoadingNotifier
version: ${pom.version}

main: au.com.addstar.notifier.PingPlugin

load: STARTUP

permissions:
  loadingnotifier.motdreload:
    default: op

commands:
  motdreload:
    permission: loadingnotifier.motdreload
    usage: /<command>
    