name: ALoadingNotifier
version: ${plugin.version}
author: Schmoller, Narimm
main: au.com.addstar.notifier.PingPlugin
description: ${project.description}
load: STARTUP

permissions:
  loadingnotifier.motdreload:
    default: op

commands:
  motdreload:
    permission: loadingnotifier.motdreload
    usage: /<command>
    